version: '3.8'

services:
  # MongoDB Database - Comment out nếu sử dụng MongoDB Atlas
  # mongodb:
  #   image: mongo:6.0
  #   container_name: viettrad-mongodb
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password123
  #     MONGO_INITDB_DATABASE: viettrad
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #     - ./server/scripts:/docker-entrypoint-initdb.d
  #   networks:
  #     - viettrad-network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: viettrad-server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      # Sử dụng MONGO_URI từ file .env hoặc trực tiếp MongoDB Atlas URI
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      EMAIL_USERNAME: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5000:5000"
    # Xóa depends_on mongodb vì sử dụng Atlas
    # depends_on:
    #   - mongodb
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - viettrad-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: viettrad-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - viettrad-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: viettrad-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
    networks:
      - viettrad-network

volumes:
  mongodb_data:

networks:
  viettrad-network:
    driver: bridge 